spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/cafe
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always