spring:
  profiles:
    default: local
  redis:
    host: localhost
    port: 6379
jwt:
  secret:
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDEDbh+6LBGVZz34H+uYtjojfjja/rCFEQ95fGXQmb72rmoqFQLHEVXQ2VTV+3Qsyd8vtRWEff5AHwb
