spring:
  config:
    activates:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:~/cafe
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
